### ISSUE TITLE
ROACH2 revision 1 pin mismatch in BEE2_hw_routes.mat

### ISSUE THREAD

**Issue by amartens** [casper-astro/mlib_devel#1]
Revision 1 of the ROACH2 has 16 GPIO pins (from 12 on revision 0). It does not have two GPIO banks like ROACH. It has no oe (output enable) pins for the GPIO. The first 8 GPIO pins are connected to the 8 LEDs on the board as well as to a header. 

The toolflow at the moment gives the option of ROACH2 having 2 GPIO ports of 12 pins with an oe pin for each. It also provides for 8 LEDs which maps to the same pins as the first 8 gpio pins. This causes various compile problems.

There is only one aux clock and a sync_in and sync_out.

There is no diff_gpio for ROACH2.

**Comment by jack-h** [comment]
Not sure if this is still an issue. ROACH2 headed towards deprecation. Won't fix.
