### ISSUE TITLE
dec_fir block complex output issue

### ISSUE THREAD

**Issue by aragorn2101** [casper-astro/mlib_devel#118]
Hi, there is an issue with the output complex data from the dec_fir block.

The block works with complex samples, it takes in real and imaginary components separately and outputs complex samples (concatenated real and imag). The issue is with the bit width of the imag at the output before concatenation. We normally set the parameters Output bit width (**x**) and Output binary pt (**y**). Then, the results are converted (by casting) just before output. The real component is correctly casted to **x_y**, but the imag component is casted to **x_(x-1)** instead.
Please find attached a screenshot of that part of the block design from Simulink.
![dec_fir_output](https://user-images.githubusercontent.com/16219423/74556222-fd24bd00-4f76-11ea-8516-be61d5cfa9da.png)

Even if this is corrected manually in the designs, the bit width parameter of the cast block is reset to **x_(x-1)**. This is producing images in the negative part spectra due to the vanishing of the imag counterpart with respect to the real part.

Thank you for attending to the problem.
Best regards.

**Comment by amartens** [comment]
Fixed in https://github.com/ska-sa/mlib_devel/commit/51a67686f3122ef1cbe6421993cb90b9399d5c74
