### ISSUE TITLE
Version checking?

### ISSUE THREAD

**Issue by cs150bf** [casper-astro/mlib_devel#13]
Version conflicts have been a problem for a long time. I don't think it's a solution per se but it would probably help if people can quickly confirm exactly what version of casper library they are using, like they could do with checking Xilinx version or Matlab version. I can't really think of how the latter could be done, though (putting the version number into library title so people can see it directly from their library browser? doesn't seem like a neat idea to me). 

I tried to make a function get_mlibVersion() that's supposed to work similar to get_xlVersion(), but it's just a very rough attempt and it doesn't quite work for several reasons:
- I cannot figure out a good way to identify our existing libraries with certain numbers/strings, so I just pulled out the newest git commit log. Not a good idea because 
  - people may not have GIT installed, but got the library through some other methods instead
  - this command doesn't quite work (for me) in Matlab as it keep getting warnings about "this terminal is not fully functional', it's just a warning but very very undesirable still, and I don't know how to fix that.
  - pulling the newest git commit log does tells you pretty much what version this library is (as git commit id) and the date. (assuming no changes have been done to the library...) But it could have been cleaner and... IDK, just better?
  - (I'm running out of time now but yeah I would appreciate better ideas on how to do this...)

mlib_devel / xps_library / get_mlibVersion.m

``` Matlab
function get_mlibVersion()

mlib_path = which('casper_library');
if isempty(mlib_path)
    disp('casper_library not found, please load casper_library first.')
end

substrind = strfind(mlib_path, '/casper_library.mdl');
mlib_path = mlib_path(1:substrind-1);
disp(['casper_library path:', mlib_path]);

type(fullfile(mlib_path, '../.git/refs/heads/master'));

currentFolder = pwd;
cd(mlib_path);
!git log --max-count=1
cd(currentFolder);

end
```

**Comment by jack-h** [comment]
Fixed in PR #90
