### ISSUE TITLE
pfb_fir_real no longer accepts parameters

### ISSUE THREAD

**Issue by kiranshila** [casper-astro/mlib_devel#176]
Since updating to the m2021a, setting any of the parameters in the `pfb_fir_real` block doesn't seem to actually do anything. I noticed this after a call to `update_casper_blocks` and it was no longer the proper size in my model.

**Comment by kiranshila** [comment]
It seems the library object for this block is missing its initialization script
![image](https://user-images.githubusercontent.com/6305359/190292234-a1f28634-f32f-4f3d-a060-853abc4381e6.png)

**Comment by mitchburnett** [comment]
#177 addresses this with some other fixes that were found to be wrong with the complex `fft` and general `pfb_fir`

**Comment by jkocz** [comment]
Closing this as #177 has been merged. Thanks @kiranshila and @mitchburnett!
