### ISSUE TITLE
Address/size inconsicencites for microblaze

### ISSUE THREAD

**Issue by kiranshila** [casper-astro/mlib_devel#184]
Since recent microblaze updates, it seems that addresses and offsets in the corresponding tcl files have not been correspondingly updated, rendering current microblaze designs inoperable.

**Comment by kiranshila** [comment]
I'm trying to fix in #183

**Comment by jkocz** [comment]
This should be addressed by #198 in m2021-dev

Will close when merge complete.

**Comment by jkocz** [comment]
This should now be fixed.
