### ISSUE TITLE
Outstanding ROACH2 yellow blocks

### ISSUE THREAD

**Issue by amartens** [casper-astro/mlib_devel#2]
## Yellow blocks completed;
- Shared BRAM (tested)
- Software register (tested)
- iADC (untested)
- katADC (untested)
- 10Ge_v2 SFP+ mezzanine (untested) 
- 10Ge_v2 CX4 mezzanine (tested)
- 1Ge (tested)
- QDR SRAM (untested)
- ADC5g (untested?)
## Outstanding yellow blocks;
- XAUI

Please update the list as things are completed/assigned/tested and we can sign the issue off when all are done.

**Comment by jack-h** [comment]
Guess no-one really used this issue for tracking :)

**Comment by david-macmahon** [comment]
Maybe no one considers any of the yellow blocks to be outstanding! :)
