### ISSUE TITLE
CASPER Actions: FPGA hardware matrix

### ISSUE THREAD

**Issue by jack-h** [casper-astro/mlib_devel#27]
Update FPGA hardware matrix with correct info. Particularly SKARAB-related memory notes

**Comment by AdamI75** [comment]
Hi John,

Here is the promised SKARAB hardware matrix block diagrams I have been promising you. I have a slide with the corrected HMC performance. I have two block diagrams: one with the toolflow supported infrastructure and one with the hardware supported infrastructure. I decided to do one diagram and I used notes stating which hardware configurations is supported. This can go in the hardware supported section of your paragraph. The Toolflow supported block diagram also uses notes, which help to explain the current limitations. We can review this when done and add if necessary.

The block diagrams are in power point form, so you may need to screen capture and convert to pdf/jpg or something like that. Let me know if you are struggling.
