### ISSUE TITLE
CASPER Actions: Ethernet Memory Map Harmonization

### ISSUE THREAD

**Issue by jack-h** [casper-astro/mlib_devel#28]
It would be easier for Microblaze Ethernet comms if all CASPER Ethernet interfaces had similar memory maps, and were also self-describing.
A suggested map  is at https://docs.google.com/document/d/19X5vTXlEistAdunGY0oHEZHcHUWnnEwmrNCCbMCdk_U/edit?usp=sharing

Post comments here!

**Comment by jack-h** [comment]
This is in the ethernet-mem-map branch. But it will break casperastro's ethernet control support, so hasn't been merged yet.

**Comment by jack-h** [comment]
Waiting in the workshop branch

**Comment by wnew** [comment]
Are we all happy that this is complete? Can I close the issue?
