### ISSUE TITLE
Ethernet multicast support

### ISSUE THREAD

**Issue by amartens** [casper-astro/mlib_devel#3]
It will be necessary (and desirable) to support multi-cast transmission of packets.  

A [patch](http://www.mail-archive.com/casper@lists.berkeley.edu/msg00555.html) by Jan Wagner supports this for the iBOB, we should look at adding this to the 10Ge, 1Ge and 10Ge_v2 blocks.

**Comment by jack-h** [comment]
Pretty sure this is now working for 10GbE onwards
