### ISSUE TITLE
Software register initial value

### ISSUE THREAD

**Issue by amartens** [casper-astro/mlib_devel#4]
It would be nice to allow software registers to have an initial value besides 0.

**Comment by jack-h** [comment]
Yes, let's actually do this!

**Comment by jack-h** [comment]
@wnew Do I recall correctly that you implemented this?

**Comment by wnew** [comment]
That is correct. 

It ended up being done in 4 changes. In the devel branch of ska-sa/mlib_devel

https://github.com/ska-sa/mlib_devel/commit/11d41e84907f9e0433119cf735257f9d23d5f0db
https://github.com/ska-sa/mlib_devel/commit/2ba854e2fe5b124127fa27a8892962826c7be412
https://github.com/ska-sa/mlib_devel/commit/11e3da1cf817a9e5d031adc64d3cab022f44fd11
https://github.com/ska-sa/mlib_devel/commit/a04b1f427e1bc6952432ea9593e0bd1dddce1474

**Comment by jack-h** [comment]
in casper-astro-soak-test
