### ISSUE TITLE
To Software register bit fields

### ISSUE THREAD

**Issue by wnew** [casper-astro/mlib_devel#46]
On the To Processor Software Register when using the bit fields functionality the simulation outputs don't match the inputs. 
![screenshot from 2018-07-25 16 51 43](https://user-images.githubusercontent.com/1127772/43208686-42d71fe4-902b-11e8-82f9-2bede8f06b46.png)

**Comment by gcallanan** [comment]
Looking at this now

**Comment by jack-h** [comment]
Fixed in PR #102
