### ISSUE TITLE
Version Info on the front page of readthedocs

### ISSUE THREAD

**Issue by jack-h** [casper-astro/mlib_devel#86]
As far as I can tell there is _no_ information in this repository explaining which versions of software are needed for which platform.

**Comment by AdamI75** [comment]
Yes, that is true. It is on the tutorials_devel readthedocs and on the Berkeley "getting_started" link though.

**Comment by jack-h** [comment]
Yeah, I think if the mlib_devel instructions are going to include an
install guide, they should probably directly contain instructions on which
versions to use :)

**Comment by bjbford** [comment]
@jack-h agreed, I totally thought our version table was there already... We should just duplicate this info: https://casper-tutorials.readthedocs.io/en/latest/#environment-setup

**Comment by jack-h** [comment]
Yes. :)

**Comment by jack-h** [comment]
PR #99 puts this at the front of the installation instructions
