### ISSUE TITLE
Compile errors if no constraints file given in yaml file

### ISSUE THREAD

**Issue by realtimeradio** [casper-astro/mlib_devel#87]
needs a `constraints: []` entry in the yaml file.
Seems like it should accept no entry at all

**Comment by jack-h** [comment]
Can't recreate this. Snap compiles fine with no `constraints` or `sources` entries in the platform YAML file.
It also looks like platform.py defaults to assigning empty lists to these values if they're not in the YAML.

**Comment by david-macmahon** [comment]
What if the YAML file has just:

```
constraints:
```

i.e. the key is present, but with a non-existent value.  Is this even legal YAML?
