### ISSUE TITLE
Shared BRAM performance

### ISSUE THREAD

**Issue by amartens** [casper-astro/mlib_devel#9]
Shared BRAMs are instantiated in different ways, 
1. If a default 32-bits-in 32-bits-out block is instantiated, an EDK dual port RAM pcore is used. This pcore optimises performance by splitting the data word across multiple BRAM primitives (if necessary) so that no output mux is required. This core cannot have different sized ports though so cannot be used in the general case.
2. In other cases, a Coregen dual port RAM is used. This has three implementation options, one that optimises for 'area', one that optimises for 'power' and one that uses specified primitives. The problem is that the 'area' option instantiates an output mux that reduces the possible performance significantly if the storage space required is larger than one BRAM in size instead of splitting the word across multiple BRAMs as with the EDK pcore above.

To optimise performance we need a dual port RAM pcore that operates like the EDK dual port RAM pcore but allows different sized interfaces.

**Comment by jack-h** [comment]
JASPER uses behavioural DP rams, not coregen cores. If performance of these is still an issue, let's raise a new issue, rather than deal with this 6 year old one!
